language: java

addons:
  apt:
    packages:
      - openjdk-6-jdk

jdk:
  - openjdk6
  - openjdk8
  - openjdk11

before_install:
  - if [[ $JAVA_HOME = *openjdk6* ]]; then jdk_switcher use openjdk6; fi

cache:
  directories:
    - $HOME/.m2
